#! /bin/sh
### BEGIN INIT INFO
# Provides:          diaspora
# Required-Start:    $local_fs $remote_fs $network $syslog redis-server
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: diaspora repository management
# Description:       diaspora repository management
### END INIT INFO

NAME=unicorn
DESC="Diaspora"
PID=/home/diaspora/diaspora-hfase/tmp/pids/unicorn.pid
START_RESQUE_PROCESS="./resque.sh"
START_DAEMON_PROCESS="RAILS_ENV=production bundle exec unicorn_rails -c config/unicorn.rb -D"


case "$1" in
  start)
        echo -n "Starting $DESC: "
		bash -lc "$START_DAEMON_PROCESS && $START_RESQUE_PROCESS"
        echo "Started $NAME."
        ;;
  stop)
        echo -n "Stopping $DESC: "
        kill -QUIT `cat $PID`
        kill -QUIT `cat $RESQUE_PID`
        echo "Stopped $NAME."
        ;;
  restart)
        echo -n "Restarting $DESC: "
        kill -USR2 `cat $PID`
        kill -USR2 `cat $RESQUE_PID`
        sleep 1
        kill -USR2 `cat $PID`
        kill -USR2 `cat $RESQUE_PID`
        sleep 1
        bash -lc "$START_DAEMON_PROCESS && $START_RESQUE_PROCESS"
        echo "Restarted $NAME."
        ;;
  *)
        echo "Usage: $NAME {start|stop|restart}" >&2
        exit 1
        ;;
esac

exit 0
